# ext-weather acceptance tests
# 
# This will boot up an instance of the ext-weather service with an instance of mountebank
# to provide service virtualization for any external dependencies.
# 
# Jason Andersen
# 2016.08.25

version: '2'
services:

  # The ext-weather service container
  ext-weather:
    image: ext-weather:latest
    environment:
      - wunderground.host.name=mountebank
      - wunderground.host.port=7575
      - wunderground.api.key=APIKEY
    ports:
      - "8081:8081"
    entrypoint: java -jar ext-weather.jar --server.port=8081
    logging:
      driver: syslog
      options:
        tag: "acceptance-testing/{{.ImageName}}"

  # log processor
  logstash:
    #build: logstash/
    image: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash:/etc/logstash/conf.d
    ports:
      - "5000:5000"

  # Service virtualization used to return test doubles for downstream dependency calls.
  mountebank:
    image: mountebank
    ports:
      - "2525:2525"
