node {
   stage 'Checkout'
   git '/opt/code/home-automation/'
   
   stage 'Build'
   def mvnHome = tool 'Maven_3.3.9'
   sh "${mvnHome}/bin/mvn -f ext-weather/service/pom.xml clean compile"
   
   stage 'Unit Test'
   sh "${mvnHome}/bin/mvn -f ext-weather/service/pom.xml test"
   step([$class: 'JUnitResultArchiver', testResults: 'ext-weather/service/target/surefire-reports/*.xml'])
   
}