#!groovy
/*
 * Groovy script to construct a build pipeline for the ext-weather service.
 */
node {

    stage 'Checkout'
    git '/opt/code/home-automation/'
    def ver = version()
    if (ver) {
    	echo "Building version ${ver}"
    }

    stage 'Build'
    def mvnHome = tool 'Maven_3.3.9'
    sh "${mvnHome}/bin/mvn -f ext-weather/service/pom.xml clean compile"
   
    stage 'Unit Test'
    sh "${mvnHome}/bin/mvn -f ext-weather/service/pom.xml test"
    step([$class: 'JUnitResultArchiver', testResults: 'ext-weather/service/target/surefire-reports/*.xml'])

    archive artifacts: '**/target/*.jar', fingerprint: true
}
def version() {
	def matcher = readFile('ext-weather/service/pom.xml') =~ '<version>(.+)</version>'
	matcher ? matcher[0][1] : null
}
